kind: Service
metadata: 
  name: webhook
  labels: 
    name: webhook
spec:
  ports:
    - name: service
      port: 8885
      targetPort: 8885
      nodePort: 32633
      protocol: TCP
  selector: 
    name: webhook
    version: "1.10"
  type: NodePort
